src/Murder.Editor/Assets/EditorSettingsAsset.cs, src/Murder.Editor/Data/TexturePacker.cs
- Adds `IgnoredTexturePackingExtensions` to the Editor settings asset so that users can specify certain file extensions they want the texture packer to ignore. 
I've been using this to allow me to create sub directories within the `resources` folder that have a `.gitkeep` file so that I can push them to github.
Also, some whitespace removal came along for the ride, I can re-submit without it if needed.
=> feat: custom ignored extensions in texture packing

Murder.sln, src/Murder/Components/Dialogs/RuleWatcherComponent.cs, src/Murder/Components/Dialogs/StateWatcherComponent.cs, src/Murder/Components/Effects/GlobalShaderComponent.cs, src/Murder/Components/Effects/RotateComponent.cs, src/Murder/Components/Graphics/FlashSpriteComponent.cs, src/Murder/Components/Grid/RoomComponent.cs, src/Murder/Components/Grid/TileGridComponent.cs, src/Murder/Components/InteractionComponents/InteractOnStartComponent.cs, src/Murder/Components/InteractionComponents/RemoveEntityOnRuleMatchAtLoadComponent.cs, src/Murder/Components/Sound/SoundWatcherComponent.cs, src/Murder/Components/Ui/WindowRefreshTrackerComponent.cs, src/Murder/Messages/HighlightMessage.cs, src/Murder/Murder.csproj, src/Murder/Systems/Graphics/CameraShakeSystem.cs, src/Murder/Systems/Utilities/FullscreenShortcutListener.cs
This integrates the Bang.Analyzers package in Murder. Good Stuff!
Glad it's already doing the works: There were many non-readonly structs (and even a class component!)
Now we need to talk about the other violations so you can confirm to me they are actual violations:
- All `IMessagerSystem`s have Filters that are taking Components. Is this correct? If yes, we need to change the analyzer, since it expects Messager systems to be filtered by messages and not components.
- All `IReactiveSystem`s are not using the `Filter` attribute at all. Is this correct? Right now Filter is mandatory for every system Watch is mandatory for reactive systems. If the Watch attribute is supposed to be used INSTEAD of the Filter attribute, then this needs to be changed in the analyzers as well
Also there's one …
=> ⚡️ Integrate analyzers

.gitignore, src/Murder.Editor/Architect.cs, src/Murder.Editor/Utilities/OperatingSystemHelpers.cs
this pr leverages sdl2 to add clipboard support for linux and fixes #19.
it also checks dependencies for existence and adds a similar check for macos.
=> add clipboard support for linux

src/Murder.Editor/Diagnostics/EditorGameLogger.cs, src/Murder/Diagnostics/GameLogger.cs
Repeated logs/warnings/errors now show how many times they have been repeated as described in #25 .
I also removed `_showDebug = false;` in `GameLogger.LogWarningImpl` since it closed the debug console every time a warning was printed, which doesn't seem right.
PS: This is my first PR, so I hope I didn't mess anything up. 
I've been really enjoying working with this engine.
=> Added a number to repeated logs

src/Murder.Editor/Data/EditorDataManager.cs
This prevents abstract types from being instantiated by EditorDataManager
=> 🐛 Filter out abstract importers

src/Murder/Utilities/Serialization/FileHelper.cs
this pr leverages `xdg-open` to open folders under linux.
xdg-open is part of the freedesktop suite so this should catch a very reasonable amount of distros.
i tested under fedora.
=> add open folder for linux

src/Murder.Editor/Data/EditorDataManager.cs
I've been setting up a project locally and I've not been able to save any assets in the editor. Setting a breakpoint just before the "Unable to save asset at path" error log showed that the paths for `_sourceResourceDirectory` and `_binResourcesDirectory` are relative paths and fail when run through `Directory.Exists`.
The issue seems to be caused by a few things:
- The relative paths for `_sourceResourceDirectory` and `_binResourcesDirectory` seem to be expecting a different root (see Path Issues below).
- The if check within SaveAssets is checking if the parent directory for the asset exists. If this is a new asset, that won't be true, so this check will fail in that case.
- SaveAssets no longer checks for the existence of the assets parent directory within the `resources` directory, …
=> SaveAssets uses absolute paths for directory checks

src/Murder.Editor/Architect.cs
There's a little bit of validation for checking the Game Profile's starting scene's integrity before launching a scene. If the Game Profile's starting scene does not exist (either because it was deleted or because of whatever serialization corruption), however, the editor would throw. Now it will instead show the console error message stating exactly what the problem is and how to fix it.
**Testing**
- Create a new World
- Change your starting scene to that new world
- Delete it
- Click play
The editor should not crash, but instead tell you what's wrong.
=> 🚓 Improve error logging for invalid world

src/Murder/Murder.csproj
This makes it possible to pack Murder and actually have it working without crashes
Some things worth noting:
- I'm placing all content inside `contentFiles\any\any\resources` instead of `contentFiles\any\net8.0\resources` to avoid having to update every time we change .NET version 
- Both `packed` and `resources` are being copied to the root of the content folder. This outputs the exact same behavior we currently have with building from a submodule, so I just kept it. The system is flexible enough should we want to add more folders
=> 🔪 Murder package configuration

src/Murder.Editor/Murder.Editor.csproj
This makes it possible to pack the Murder editor and actually have it working without crashes
One question I have is if we still need to pack the MonoGame bits for the NuGet package, but I kept it in there for good measure 🤔
=> 🎁 Make the editor packable

src/Murder/Core/Graphics/Color.cs
This could be, alternatively, making color a record, but since it already overrides `ToString` I think we might as well just make this change instead.
=> 🎨 Override color equality operators

src/Murder/Core/Graphics/Color.cs
All fields in color could be made readonly without breaking compiler checks.  There's tons of methods for color manipulation, so it only makes sense to make it readonly as well. This also adds some docs around the color available values
This could be couple with marking it as a `record` to allow for the syntax `color with { R = 0.4f }`, but I'll let the maintainers decide if this is worth merging and whether to follow up with this change
=> 🔒 Make colors readonly

src/Murder.Editor/EditorScene.cs, src/Murder.Editor/EditorScene_Editors.cs
This makes it so that relevant Ctrl+[Key] commands are represented as Cmd+[Key] on macOS. 
Cmd+W specifically still closes the editor, but that can only be fixed on Murder with drastic changes, so for now it won't be fixed
=> 🍎 Apple-Aware shortcuts

src/Murder/Core/Geometry/Point.cs
This does a series of tiny improvements to the point class, namely:
- public member documentation, including clarifying behavior that I needed to check every now and then
- Marking the `ToVector2` method as readonly
- Inlining the static readonly properties
- Adding a Deconstruct method for inline tuple creation in an idiomatic way
=> 🧼 Tidy up the Point class

src/Murder/Services/RenderServices.cs
I wonder why some render services methods were extensions on top of Batch2D while some were not, so I just made them all extensions. It's convenient, reduces bloat and one can still use the old syntax if should they prefer it.
=> 👨🏽‍🎨 Make RenderServices methods extension methods

src/Murder/Core/Graphics/DrawInfo.cs, src/Murder/Services/RenderServices.cs
This adds some additional options for the outline rendering. The code was already there, I just made it more configurable
The choice of names was made so as to not disrupt the existing behaviour (as in: the None/Top/Full entries of the enum all have the same behaviour as before)
=> 🔲 Add flexibility to outline rendering

src/Murder.Editor/EditorScene.cs, src/Murder.Editor/EditorScene_Explorer.cs, src/Murder.Editor/EditorScene_Shortcuts.cs, src/Murder/Core/Input/Chord.cs, src/Murder/Core/Input/PlayerInput.cs
This refactors the way the menu bar is laid out so that:
- All shortcuts exist in the same place
- All menu bar action need to be assigned a shortcut before they can be rendered.
On its own this already has benefits over the current approach, but the endgame is to implement a global action runner/command palette that allows users to discover all shortcuts. A dirty prototype of what I mean can be seen in the gif below.
=> 🍸 Tidy up the menu bar

src/Murder.Editor/Utilities/AssetsFilter.cs, src/Murder.Editor/Utilities/Gui/SearchBox.cs, src/Murder.Editor/Utilities/ReflectionHelper.cs
I'm consistently getting crashes (Rider 2023.3.2, both on macOS and Windows) whenever I exit the game from the editor. This completely ruins the fast paced experience. The error I'm getting is the following:
```
Unhandled exception. System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.CodeAnalysis.CSharp, Version=4.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. …
```
=> 💥 Fix crash when quitting to editor

src/Murder/Core/Graphics/RenderContext.cs
This adds two extra points to render context, which basically removes most needs to override the End method!
One point happens right after the main game has been drawn and the other one happens right after the UI has been drawn. This means one can now create any number of additional batches and end said batches in these extension points would allow to draw at the correct target at the correct time without having to copy all the code inside the `End` method over to one's project!
=> 👨🏽‍🎨 Add hook points to render context

src/Murder.Editor/Assets/EditorSettingsAsset.cs, src/Murder.Editor/CustomEditors/PrefabAssetEditor.cs, src/Murder.Editor/CustomEditors/WorldAssetEditor.cs, src/Murder.Editor/Systems/Debug/SystemsDiagnosticsSystem.cs, src/Murder.Editor/Systems/EditorSystem.cs, src/Murder/Core/Graphics/RenderContext.cs, src/Murder/Data/GameDataManager.cs
This removes a bunch of code that is too specific from the main rendering pipeline. Core changes:
- The first shader from `IShaderProvider` is no longer assumed to be a custom shader that should be used for the entire game
- The concept of a "CustomShader" has been removed entirely, since one can achieve the same with the existing extension points
- Assumptions about the basic shader (like its parameters or technique names) have been removed
- A BatchPreviewState step has been removed
=> 🕶️ Simplify Custom Shader logic

src/Murder.Editor/Systems/SpriteRenderDebugSystem.cs, src/Murder/Components/Graphics/RenderedSpriteCacheComponent.cs, src/Murder/Core/Graphics/Batch/SpriteBatchItem.cs, src/Murder/Core/Graphics/DrawInfo.cs, src/Murder/Core/Graphics/ImageFlip.cs, src/Murder/Core/Graphics/Mask2D.cs, src/Murder/Services/RenderServices.cs, src/Murder/Systems/Agents/AgentSpriteSystem.cs, src/Murder/Systems/Graphics/ParticleRendererSystem.cs, src/Murder/Systems/Graphics/SpriteRenderSystem.cs, src/Murder/Utilities/DirectionHelper.cs
I could heavily simplify a little something by allowing my sprite to rotate freely instead of adding multiple sprites. When trying to enable that in murder, I noticed that we already have everything in place, including an enum for controlling how the flipping should happen, but we were limiting it to horizontal flipping only on the `DrawInfo`. This patches that behavior
=> 😵‍💫 Enable flipping in every direction

src/Murder.Editor/Assets/EditorSettingsAsset.cs, src/Murder.Editor/EditorScene.cs, src/Murder.Editor/EditorScene_Shortcuts.cs
This is the 0 IQ solution to automatically reloading the shaders: 
- We already have a shader reloading mechanism
- .NET has an out-of-the-box, cross platform file system watcher
I just smashed the two together. Some notes:
- The lock is in place because the FileSystemWatcher is multithreaded and the shader reloading needs to happen on the main thread.
- I thought about optimizing to only reload the shader we need, but, by definition, when the user is editing the shader they won't be looking at the editor, so we can afford to hiccup the main thread when no one is looking 🤷 
- There's a toggle to disable shader hot reloading, should the user not need it or would rather not use it.
=> 🔥 Shader Hot Reloading

src/Murder.Editor/EditorScene.cs, src/Murder.Editor/EditorScene_Shortcuts.cs, src/Murder.Editor/Utilities/Gui/SearchBox.cs
This implements a command palette, which allows for searching and executing all commands from the menu bar. This is a followup of #59, meaning that all new shortcuts added to the menu bar will automatically be searchable from the command palette.
Usage is simple: Press Ctrl (or Cmd) + Shift + A, which will bring up a search box that can be filtered by typing. Selecting any command from that searchbox will execute that command; pressing esc will dismiss the command palette.
I had to create a parameterized overload of `Search<T>` so as to not break the current behavior of all search boxes while allowing for its size to change in this new use case. This can be useful in more scenarios (since right now all search boxes have the same size, we can make them have different size settings based on …
=> 🎨 Command palette

src/Murder.Editor/Systems/EditorCameraControllerSystem.cs, src/Murder.Editor/Systems/GenericSelectorSystem.cs
an attempt at addressing #74 
- when an entity is selected, using the arrow keys will change its position by 1 pixel in the corresponding direction
- holding shift while doing this will move by 1 tile
- holding shift while dragging an entity will constrain it to the direction you are dragging in
=> feat: improve entity movement in editor

src/Murder/Systems/Agents/AgentSpriteSystem.cs
without this change, tint was only applied for `SpriteComponent` but not `AgentSpriteComponent`
=> handle tint in AgentSpriteSystem

src/Murder/Assets/Graphics/TilesetAsset.cs, src/Murder/Services/TileServices.cs
This is a proposed fix (closes #86) for an issue that I just submitted. I've also taken the liberty to tweak some comments that I _believe_ were incorrect.
Please let me know if I'm mistaken in my analysis of anything, just because it's corrected the issue that I've seen does not mean that I haven't totally misunderstood the mechanisms at play. Thanks!
=> Small adjustment to tile automap sort order calculations

src/Murder/Components/Graphics/NineSliceComponent.cs
I need to programatically modify a NineSliceComponent. Many other components already offer such pattern, so I added it to this one as well.
=> 9️⃣ Allow NineSliceComponent to be modified

src/Murder.Editor/Utilities/Gui/ImGuiHelpers.cs
When your enum has the `Flags` attribute, there's a cool checkbox editor that automatically selects/deselects the correct checkboxes based on whether the asset's property has that flag set or not. For enum values that have multiple bits set, however, having any bit set will cause the checkbox to be checked, which is not the correct behavior.
https://github.com/user-attachments/assets/c29c239a-8fe2-4586-8189-e6711bd38936
This PR changes the verification of each bit to be `!A || B` instead, making it so that a value which needs both bits set will only be checked if ALL needed bits are set.
https://github.com/user-attachments/assets/60ce608c-85b1-4324-9207-321b1fa63a5e
=> ✅ Respect enabled flags in editor

src/Murder/Core/Particles/Data/EmitterShape.cs, src/Murder/Data/GameDataManager_Save.cs
This hardens the particle system against some common crashes by:
- Ensuring we're handling all possible emitter shapes.
- Initializing the `CurrentPalette` field so it doesn't crash when we're trying to pick the particle colors.
=> 🥳 Harden particle system

src/Murder.Editor/Services/EditorServices.cs, src/Murder/Utilities/GridHelper.cs
This makes it so that holding control while editing a collider's shape snaps its position and size to the grid.
=> Snap collider to grid while holding ctrl
